### ISSUE TITLE
What is the status of the project?

### ISSUE THREAD

**Issue by privettoli** [pjjjv/app-router-dart-test#1]
Hi, I need to use app-router in my dart application with polymer, is it already ready to use?

**Comment by pjjjv** [comment]
Hey, good question! I also recognized the need for a good router as I have been trying various bits of code that don't work. I technically finished the port last week, but I hit a snag: Dart doesn't work well with polymer when it comes to dynamic html imports, so this makes lazy loading hard, and defies the purpose of app-router. More: https://code.google.com/p/dart/issues/detail?id=22125 . This repo contains the latest test code, but not clean nor usable. I have an offline app-router-dart repo that I did not push yet, as I said, because it is not working.

However... I came across some nice code that at least allows to lazy load a page if you know upfront which polymer elements it's going to use (all elements are loaded at start though), so I have some new hopes and plan to work on this soon. https://bitbucket.org/andersmholmgren/ah_polymer_stuff

In my Akepot repository I am using more-routing as an alternative currently. It's very limited and doesn't work great, but it 'routes'.

**Comment by privettoli** [comment]
Sorry, but I didn't understand you. Why does Javascript code not work with Dart?
I tried your library, but no success. Then I tried simply import js app-route, but now I have

```
Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': Nodes of type 'HTML' may not be inserted inside nodes of type '#document'. polymer.min.js:13(anonymous function) polymer.min.js:13(anonymous function) polymer.min.js:13(anonymous function) polymer.min.js:13
Uncaught TypeError: object is not a function paper-ripple.html:283(anonymous function) paper-ripple.html:283(anonymous function) paper-ripple.html:473
Uncaught TypeError: object is not a function paper-shadow.html:41
Uncaught TypeError: undefined is not a function polymer-mixin.js:7
Uncaught TypeError: object is not a function paper-button.html:142
Uncaught TypeError: Cannot read property 'loadStyles' of undefined polymer.min.js:14
Exception: NoSuchMethodError: method not found: 'whenPolymerReady'
Receiver: Instance of 'JsObject'
Arguments: [Closure: () => dynamic] package:polymer/src/loader.dart:105
```

So is there a solution (any solution) for me to continue develop important part of the application instead of investigations how to make it working (after I used app-route in js, dart looks like a problem in my architecture).

**Comment by pjjjv** [comment]
You have 3 options I think: 1. use more-routing. 2. use javascript instead of dart. 3. wait a bit and see if I can get it working.

**Comment by pjjjv** [comment]
Released a working version. -> app-router-dart, or app-router in Pub. Please submit future issues regarding component there in github.
